# Generated by Django 4.0 on 2021-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('firstName', models.CharField(max_length=20, null=True)),
                ('lastName', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
                ('jobTitle', models.CharField(max_length=50, null=True)),
                ('programming', models.CharField(max_length=200, null=True)),
                ('languageKnown', models.CharField(max_length=200, null=True)),
                ('linkedIn', models.CharField(max_length=200, null=True)),
                ('resume', models.CharField(max_length=200, null=True)),
                ('github', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
