# Generated by Django 4.0 on 2021-12-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaApi', '0002_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea', to='IdeaApi.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notiId', models.AutoField(primary_key=True, serialize=False)),
                ('notiType', models.CharField(choices=[('Upvote', 1), ('Downvote', 2), ('Followed', 3), ('Suggested', 4), ('Friend', 5), ('Collaboration', 6)], max_length=20, null=True)),
                ('notiTime', models.TimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='IdeaApi.user')),
            ],
        ),
    ]
